In [1]:
 # Following libraries should be imported to run the experiment........
import numpy as np
import pandas as pd

In [2]:
# Download and save the file in your directory.
# Read the file using pandas library.
df = pd.read_csv("Medicalpremium.csv")
df

,Age,Diabetes,BloodPressureProblems,AnyTransplants,AnyChronicDiseases,Height,Weight,KnownAllergies,HistoryOfCancerInFamily,NumberOfMajorSurgeries,PremiumPrice
0,45,0,0,0,0,155,57,0,0,0,25000
1,60,1,0,0,0,180,73,0,0,0,29000
2,36,1,1,0,0,158,59,0,0,1,23000
3,52,1,1,0,1,183,93,0,0,2,28000
4,38,0,0,0,1,166,88,0,0,1,23000
...,...,...,...,...,...,...,...,...,...,...,...
981,18,0,0,0,0,169,67,0,0,0,15000
982,64,1,1,0,0,153,70,0,0,3,28000
983,56,0,1,0,0,155,71,0,0,1,29000
984,47,1,1,0,0,158,73,1,0,1,39000
985,21,0,0,0,0,158,75,1,0,1,15000

In [3]:
df = df.assign(Age=pd.cut(df['Age'], 
                               bins=[0, 10.5, 20.5, 30.5, 40.5, 50.5, 60.5, 70.5, 999], 
                               labels=['0->10', '11->20', '21->30', '31->40', '41->50', '51->60', '61->70', '70+']))

In [4]:
df = df.assign(Diabetes=pd.cut(df['Diabetes'], 
                               bins=[-0.5, 0.5, 999], 
                               labels=['No', 'Yes']))

In [5]:
df = df.assign(BloodPressureProblems=pd.cut(df['BloodPressureProblems'], 
                               bins=[-0.5, 0.5, 999], 
                               labels=['No', 'Yes']))

In [6]:
df = df.assign(AnyTransplants=pd.cut(df['AnyTransplants'], 
                               bins=[-0.5, 0.5, 999], 
                               labels=['No', 'Yes']))

In [7]:
df = df.assign(AnyChronicDiseases=pd.cut(df['AnyChronicDiseases'], 
                               bins=[-0.5, 0.5, 999], 
                               labels=['No', 'Yes']))

In [8]:
df = df.assign(HistoryOfCancerInFamily=pd.cut(df['HistoryOfCancerInFamily'], 
                               bins=[-0.5, 0.5, 999], 
                               labels=['No', 'Yes']))

In [9]:
df = df.assign(NumberOfMajorSurgeries=pd.cut(df['NumberOfMajorSurgeries'], 
                               bins=[-0.5, 1.1, 999], 
                               labels=['Low', 'High']))

In [10]:
print(df)

        Age Diabetes BloodPressureProblems AnyTransplants AnyChronicDiseases  \
0    41->50       No                    No             No                 No
1    51->60      Yes                    No             No                 No
2    31->40      Yes                   Yes             No                 No
3    51->60      Yes                   Yes             No                Yes
4    31->40       No                    No             No                Yes
..      ...      ...                   ...            ...                ...
981  11->20       No                    No             No                 No
982  61->70      Yes                   Yes             No                 No
983  51->60       No                   Yes             No                 No
984  41->50      Yes                   Yes             No                 No
985  21->30       No                    No             No                 No

     Height  Weight  KnownAllergies HistoryOfCancerInFamily  \
0       155      57               0                      No
1       180      73               0                      No
2       158      59               0                      No
3       183      93               0                      No
4       166      88               0                      No
..      ...     ...             ...                     ...
981     169      67               0                      No
982     153      70               0                      No
983     155      71               0                      No
984     158      73               1                      No
985     158      75               1                      No

    NumberOfMajorSurgeries  PremiumPrice
0                      Low         25000
1                      Low         29000
2                      Low         23000
3                     High         28000
4                      Low         23000
..                     ...           ...
981                    Low         15000
982                   High         28000
983                    Low         29000
984                    Low         39000
985                    Low         15000

[986 rows x 11 columns]